 
# Add Che link on PRs
name: devfile-latest-release

on:
  push:
    tags:
    - '*'
    
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
        
    - name: Generate schema from source
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Generate the schema.json
      run: build.sh
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          schemas/latest/devfile.json
